# Analíse exploratória do "The Hot 100 Billboard" da última década

## 1) Importação de Libs + Limpeza Inicial

Como o dataset possui mais de 300 mil linhas, com dados desde o ano de 1958, optamos por utilizar somente as informações da década passada

In [15]:
import matplotlib as plt
import pandas as pd
import numpy as np

plt.rcParams["date.autoformatter.day"] = "%d/%m/%Y"

In [18]:
base = r'charts.csv'
charts = pd.read_csv(base)
charts = charts.rename(columns={"date": "Data", "rank": "Ranking", "song": "Música", "artist": "Artista", "last-week": "Última Semana", "peak-rank": "Maior Posição", "weeks-on-board": "Semanas no 'Board'"})
charts["Data"] = pd.to_datetime(charts["Data"])
charts = charts[
    (charts["Data"].dt.year >= 2011)
]

In [19]:
display(charts)

,Data,Ranking,Música,Artista,Última Semana,Maior Posição,Semanas no 'Board'
0,2021-11-06,1,Easy On Me,Adele,1.0,1,3
1,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
3,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
4,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18
...,...,...,...,...,...,...,...
56695,2011-01-01,96,Loca,Shakira Featuring El Cata or Dizzee Rascal,90.0,32,11
56696,2011-01-01,97,For The First Time,The Script,NaN,97,1
56697,2011-01-01,98,Letting Go (Dutty Love),Sean Kingston Featuring Nicki Minaj,86.0,36,20
56698,2011-01-01,99,"Baby, It's Cold Outside",Glee Cast,57.0,57,2
56699,2011-01-01,100,Oh Santa!,Mariah Carey,NaN,100,1

## Informações gerais do dataset

In [20]:
charts.describe()

,Data,Ranking,Última Semana,Maior Posição,Semanas no 'Board'
count,56700,56700.000000,50120.000000,56700.000000,56700.000000
mean,2016-06-04 00:00:00,50.500000,46.975958,38.254921,12.280864
min,2011-01-01 00:00:00,1.000000,1.000000,1.000000,1.000000
25%,2013-09-14 00:00:00,25.750000,23.000000,11.000000,4.000000
50%,2016-06-04 00:00:00,50.500000,46.000000,35.000000,10.000000
75%,2019-02-23 00:00:00,75.250000,70.000000,62.000000,17.000000
max,2021-11-06 00:00:00,100.000000,100.000000,100.000000,90.000000
std,NaN,28.866325,27.913408,29.158694,10.383680